#!/usr/bin/env python3
import rospy
from geometry_msgs.msg import Twist


def main():
    rospy.init_node(name='husky_controller')

    pub = rospy.Publisher(
        name="husky_velocity_controller/cmd_vel",
        data_class=Twist,
        queue_size=1
    )

    rate = rospy.Rate(10)  # 10hz
    msg = Twist()
    msg.linear.x = 0.75
    msg.angular.z = 0.5
    while not rospy.is_shutdown():
        pub.publish(msg)
        rate.sleep()

if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass
